
services:
  postgres:
    image: postgres:16
    container_name: jee_postgres
    restart: always
    environment:
      POSTGRES_DB: clinique
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_clinic
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@java.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"


volumes:
  postgres_data:
